let elements = [
    {
        id: 1,
        title: "Birth",
        description: "...",
        dateRange: "November 14th 1998",
        loc: "Somewhere, Kuwait",
        tag: "other",
        icon: "",
    },
    {
        id: 2,
        title: "Graduated Highschool",
        description: "...",
        dateRange: "June 2016",
        loc: "Somewhere, Kuwait",
        tag: "Education",
        icon: "",
    },
    {
        id: 3,
        title: "Began University",
        description: "Chemical & Biological Engineering Department",
        dateRange: "November 1998",
        loc: "Ames, Iowa",
        tag: "Education",
        icon: "",
    },
    {
        id: 4,
        title: "",
        description: "...",
        dateRange: "November 1998",
        loc: "Somewhere, Kuwait",
        tag: "other",
        icon: "",
    },
    {
        id: 5,
        title: "Birth",
        description: "...",
        dateRange: "November 1998",
        loc: "Somewhere, Kuwait",
        tag: "other",
        icon: "",
    },
    {
        id: 6,
        title: "Birth",
        description: "...",
        dateRange: "November 1998",
        loc: "Somewhere, Kuwait",
        tag: "other",
        icon: "",
    },
    {
        id: 7,
        title: "Birth",
        description: "...",
        dateRange: "November 1998",
        loc: "Somewhere, Kuwait",
        tag: "other",
        icon: "",
    },
    {
        id: 8,
        title: "Birth",
        description: "...",
        dateRange: "November 1998",
        loc: "Somewhere, Kuwait",
        tag: "other",
        icon: "",
    },
    {
        id: 9,
        title: "Birth",
        description: "...",
        dateRange: "November 1998",
        loc: "Somewhere, Kuwait",
        tag: "other",
        icon: "",
    },
    {
        id: 10,
        title: "Birth",
        description: "...",
        dateRange: "November 1998",
        loc: "Somewhere, Kuwait",
        tag: "other",
        icon: "",
    },
];

export default elements;
